### ISSUE TITLE
Failed to load NIF library

### ISSUE THREAD

**Issue by nitingupta910** [hansihe/rustler#141] opened 2018-05-07 18:45 UTC
I have an elixir umbrella app `apps/nif_io` which provides elixir interface for another rust library `rs/graph` which is in a workspace. With such a setup I get this error when I do `mix test`:
```
11:33:34.289 [warn]  The on_load function for module Elixir.NifIo returned:
{:error, {:load_failed, 'Failed to load NIF library /home/ngupta/temp/nifbug/_build/test/lib/nif_io/priv/native/libio: \'libstd-c10c01f750e28d27.so: cannot open shared object file: No such file or directory\''}}
```

Here is the repo which reproduces the issue:
https://github.com/nitingupta910/nifbug
(just type `mix test` after cloning the repo)

**Versions**
elixir: 1.6.5
rrlang: 20.3.5
rust: 1.25
os: Ubuntu 16.04.4 LTS

**Comment by evnu** [comment] 2018-06-07 12:32
I had a similar issue, which I solved by removing the crate-type ("dylib") from the crates `[lib]` section. `crate-type = "rlib"` worked for me as well.

**Comment by nitingupta910** [comment] 2018-06-08 13:14
If I remove crate-type or set it to "rlib", I get:

on Linux:
```
** (File.CopyError) could not copy from "/scratch/temp/nifbug/_build/test/rustler_crates/io/debug/libio.so" to "priv/native/libio.so": no such file or directory
```

on macOS:
```
** (File.CopyError) could not copy from "/Users/ngupta/src/nifbug/_build/test/rustler_crates/io/debug/libio.dylib" to "priv/native/libio.so": no such file or directory
```

**Comment by evnu** [comment] 2018-06-14 13:46
It seems that [this answer on stackoverflow](https://stackoverflow.com/a/44014552/436853) can answer this question. I am able to reproduce this issue when I create a workspace containing two crates (one NIF, one helper; I can upload it to github if needed). When building the NIF, `cargo build -v` outputs the following:

```
...
rustc --crate-name withworkspace withworkspace/src/lib.rs --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C debuginfo=2 -C metadata=5f087f4256b2b3b0 --out-dir /home/mo/tools/rustler_with_workspaces/native/target/debug/deps -C incremental=/home/mo/tools/rustler_with_workspaces/native/target/debug/incremental -L dependency=/home/mo/tools/rustler_with_workspaces/native/target/debug/deps --extern rustler=/home/mo/tools/rustler_with_workspaces/native/target/debug/deps/librustler-003064f4ae0eced2.rlib --extern rustler_codegen=/home/mo/tools/rustler_with_workspaces/native/target/debug/deps/librustler_codegen-7ec3b728b31a9365.so --extern adder=/home/mo/tools/rustler_with_workspaces/native/target/debug/deps/libadder-b882c9343e6f11dc.rlib --extern lazy_static=/home/mo/tools/rustler_with_workspaces/native/target/debug/deps/liblazy_static-31275cefe6766f67.rlib
```

The linking issue is caused by `-C prefer-dynamic`. I am using rustup, so stdlib is not in the systems default search paths. When I add the corresponding path to `LD_LIBRARY_PATH`, linking works. I see two options two resolving this:

1. Set `LD_LIBRARY_PATH`
1. Get rid of `prefer-dynamic` in workspaces

@nitingupta910 Do you also use rustup? Can you confirm that `rustc` is called with `-C prefer-dynamic`?

**Comment by nitingupta910** [comment] 2018-06-14 15:20
@evnu I’m not compiling NIF directly; it is compiled by a mix task defined by rustler_mix. I see that the task uses rustup to invoke the compiler. I need to dig further to see why linker path is not set correctly only when using workspace.

To repro this issue you can clone repo I mentioned in the bug description and do: ‘mix deps.get && mix test’

**Comment by evnu** [comment] 2018-06-15 07:42
With your example project, the following works on my machine:

```
LD_LIBRARY_PATH=/home/mo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib mix test
```

So it is indeed an issue with the library search path. I do not understand yet why Rust links stdlib dynamically when building within a workspace, but not if the NIF is built directly.

Some info on my setup:

* ArchLinux
* Rust: `rustc 1.26.0 (a77568041 2018-05-07)` (from rustup)
* Elixir: 1.6.5

**Comment by scrogson** [comment] 2018-06-15 16:55
@evnu thank you so much for your help in getting to the root of this issue!

I'm going to do some tests and we'll probably end up making `cdylib` the default `crate-type` in the generator.

**Comment by nitingupta910** [comment] 2018-06-15 18:10
@evnu I changed to cdylib and it works. Thanks a lot!

**Closed** 2019-01-05 00:44 UTC
